apiVersion: v1
kind: Pod
metadata:
  name: tomcat-latest
  namespace: my-ns
  labels:
    app: my-app
  annotations:
     desc: Tomcat latest
spec:
  containers:
  - name: tomcat-latest
    image: tomcat
    imagePullPolicy: Always
    ports:
     - containerPort: 8081
